[package]
name = "rust-pkg-config-find"
version = "0.1.0"
authors = ["Zahari Petkov <zahari@balena.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pkg-config = "*"
